### PR TITLE
Fix pkg_search_module

### PR DESCRIPTION
**Pull request by lukicdarkoo**
Fixes:
```
CMake Error at CMakeLists.txt:21 (pkg_search_module):
  Unknown CMake command "pkg_search_module".
```

### CODE REVIEW

**Comment by borongyuan** [comment]
Hi, have you tested this package on Windows? Usually this line is not necessary for Linux. I've only heard of such problems on Windows. So I am curious about your development environment.

**Comment by lukicdarkoo** [comment]
I had the issue on Ubuntu 22.04 in a Docker container

**Comment by borongyuan** [comment]
Thanks, I can finally reproduce this issue. I think this issue is not related to Docker. It's just that several Docker images I know have switched to Cyclone DDS. If the environment variable "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" is set, you will encounter this problem when compiling. As odd as it is, it is true. ROS2 developers have encountered quite a few strange problems with DDS. We'll take a closer look at what this is all about later.

**Comment by avielbr** [comment]
Thanks for adding the directions parameter. While I agree @borongyuan's suggestion to use transmissions is more robust, I am having trouble getting it working.

@lukicdarkoo, I'm finding that after adding the directions parameter and setting the directions of each axis of my diff. drive robot (see below) the FORWARD / REVERSE movements are indeed correct, but the Z axis rotation is showing backwards. The physical robot's wheels are rotating the correct way, but when viewing on RViz2 I'm seeing the opposite direction. Wondering if you have any ideas about this.

```
...
      <xacro:if value="${enable_joint0}">
        <joint name="${joint0_name}">
          <param name="serial_number">${serial_number}</param>
          <param name="direction">1</param>
          <param name="axis">0</param>
          <param name="enable_watchdog">1</param>
          <param name="watchdog_timeout">0.1</param>
        </joint>
      </xacro:if>

      <xacro:if value="${enable_joint1}">
        <joint name="${joint1_name}">
          <param name="serial_number">${serial_number}</param>
          <param name="direction">-1</param>
          <param name="axis">1</param>
          <param name="enable_watchdog">1</param>
          <param name="watchdog_timeout">0.1</param>
        </joint>
      </xacro:if>
...
```

**Comment by lukicdarkoo** [comment]
> Thanks, I can finally reproduce this issue. I think this issue is not related to Docker. It's just that several Docker images I know have switched to Cyclone DDS. If the environment variable "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" is set, you will encounter this problem when compiling. As odd as it is, it is true. ROS2 developers have encountered quite a few strange problems with DDS. We'll take a closer look at what this is all about later.

Good catch, I was using Cyclone DDS but I didn't think it was worth of mentioning.

@avielbr I implemented reversing and it was working fine, but deleted it eventually as it makes the implementation ugly. I simply switched the wires on ODrive

**Pull request merged**
